name: CI Pipeline

on: 
  push:
    branches:
      - main

jobs:
  # Job de test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run tests
        run: echo "Running tests..."

  # Job de build
  build:
    runs-on: ubuntu-latest
    needs: test  # Le job de build dépend du job test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run build step
        run: echo "Building the project..."

  # Job de deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Le job de deploy dépend du job build
    steps:
      - name: Deploy step
        run: echo "Deploying the project..."
